import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { setupGPUPadRemoval } from '../src/gpu-pad-removal.ts';

test('worn pad material only recedes during an inward scraper drag', () => {
  const oldDocument = globalThis.document;
  const events = new EventTarget();
  const output = { value: '' };
  globalThis.document = Object.assign(events, { querySelector: () => output });
  try {
    const gpu = new THREE.Group();
    const originalMaterial = new THREE.MeshStandardMaterial({ color: '#888888' });
    const piece = new THREE.Mesh(new THREE.BoxGeometry(.18, .024, .22), originalMaterial);
    piece.name = 'memory-residue-0-1';
    piece.position.set(-1.475, .146, -.46);
    gpu.add(piece);
    let coolerRemoved = false;
    const notices = [];
    const removal = setupGPUPadRemoval(gpu, () => coolerRemoved, text => notices.push(text));
    const at = x => new THREE.Vector3(x, .158, -.46);
    const ray = x => new THREE.Ray(new THREE.Vector3(x, 1, -.46), new THREE.Vector3(0, -1, 0));
    assert.equal(removal.begin(piece, at(-1.415)), false);
    assert.equal(piece.visible, true);
    coolerRemoved = true;
    assert.equal(removal.begin(piece, at(-1.475)), false);
    assert.equal(removal.begin(piece, at(-1.385)), true);
    assert.notEqual(piece.material, originalMaterial);
    assert.equal(piece.material.emissive.getHexString(), 'ff7777');
    assert.equal(piece.children.length, 2);
    removal.end();
    assert.equal(piece.material, originalMaterial);
    assert.equal(piece.children.length, 0);
    assert.equal(removal.begin(piece, at(-1.415)), true);
    assert.equal(removal.progress, 0);
    assert.equal(removal.drag(ray(-1.395)), false);
    assert.equal(removal.progress, 0);
    assert.equal(removal.drag(ray(-1.445)), true);
    assert.ok(removal.progress > 0 && removal.progress < 1);
    assert.ok(piece.scale.x < 1 && piece.visible);
    assert.ok(piece.scale.z < 1);
    assert.equal(removal.drag(ray(-1.565)), true);
    assert.equal(removal.progress, 1);
    assert.equal(piece.visible, false);
    assert.equal(piece.material, originalMaterial);
    assert.match(output.value, /100%/);
    document.dispatchEvent(new Event('bench-next-job'));
    assert.equal(removal.progress, 0);
    assert.equal(piece.visible, true);
    assert.equal(piece.scale.x, 1);
    assert.equal(piece.position.x, -1.475);
    assert.equal(removal.begin(piece, new THREE.Vector3(-1.475, .158, -.39)), true);
    assert.equal(removal.drag(new THREE.Ray(new THREE.Vector3(-1.475, 1, -.44), new THREE.Vector3(0, -1, 0))), true);
    assert.ok(removal.progress > 0 && removal.progress < 1);
    removal.end();
    assert.equal(piece.material, originalMaterial);
    removal.dispose();
  } finally {
    globalThis.document = oldDocument;
  }
});
